### ISSUE TITLE
pls help to run on Windows computer python 2

### ISSUE THREAD

**Issue by Sandy4321** [jeppe/TIIREC#1]
error message is 
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

D:\Recomender_Sysytems\code\TIIREC-master>python TIIREC.py --trainpath .\data\tr
ain.data --testpath .\data\test.data --dimension 10 --dataname abc
Traceback (most recent call last):
  File "TIIREC.py", line 581, in <module>
    dataset = args.dataname)
  File "TIIREC.py", line 80, in exe
    train(traset = traset, vset = tset)
  File "TIIREC.py", line 103, in train
    globalRecalls, sparseRecall = MapReduceEvaluation(tset = vset, num_workers =
 NUMWORKERs)
  File "TIIREC.py", line 267, in MapReduceEvaluation
    chunksize = 1)
  File "C:\Users\SanderOct27\Anaconda2\lib\multiprocessing\pool.py", line 251, i
n map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Users\SanderOct27\Anaconda2\lib\multiprocessing\pool.py", line 567, i
n get
    raise self._value
TypeError: 'int' object has no attribute '__getitem__'

D:\Recomender_Sysytems\code\TIIREC-master>

**Comment by Sandy4321** [comment]
is it this problem
https://stackoverflow.com/questions/2782961/yet-another-confusion-with-multiprocessing-error-module-object-has-no-attribu

**Comment by Sandy4321** [comment]
I use 
multiprocessing.__version__
'0.70a1'
Python version 2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
